image: rocker/tidyverse
stages:
    - install
    - test
install:
    stage: install
    script:
        - apt-get update -qq
        - apt-get install -y libjpeg-dev libgdal1-dev libproj-dev
        - R -e 'devtools::install_github("dkahle/ggmap")'
        - R -e 'install.packages(c("plotKML", "rgdal"))'
        - R CMD build . --no-build-vignettes --no-manual
        - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
        - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual
        - R -e 'devtools::test()'
